kind: pipeline
name: default

workspace:
  path: /careerintlinc-tech-share

volumes:
  - name: webroot
    host:
      path: /root/www
  - name: pnpm-cache
    host:
      path: /root/.pnpm-cache

trigger:
  branch:
    - master

steps:
  - name: build
    image: node:20.13.0
    volumes:
      - name: pnpm-cache
        path: /careerintlinc-tech-share/.pnpm-store
    commands:
      - npm i -g pnpm
      - pnpm i
      - pnpm build
    environment:
      HUSKY: 0

  - name: deploy-upload-cdn
    image: plugins/s3
    settings:
      endpoint: https://cos.ap-hongkong.myqcloud.com
      region: ap-hongkong
      bucket: paperplane-cdn-1253277322
      access_key:
        from_secret: COS_SECRET_ID
      secret_key:
        from_secret: COS_SECRET_KEY
      source: ./dist/**/*
      target: /careerintlinc-tech-share
      strip_prefix: dist

  - name: deploy
    image: ubuntu:22.04
    volumes:
      - name: webroot
        path: /webroot
    commands:
      - mkdir -p /webroot/careerintlinc-tech-share/
      - cp -rf ./dist/* /webroot/careerintlinc-tech-share/

